k8s_log_watcher/kube.py

- Refactor config loading
- Fix typo

Fix kube client & typo

---

MANIFEST.in
setup.py

Fix missing templates in package

Include templates in package

---

k8s_log_watcher/kube.py
k8s_log_watcher/main.py
k8s_log_watcher/templates/appdynamics.job.jinja2

+ Add option to use API proxy (for offloading auth and dropping the use of serviceaccount)
+ Fix appdynamics template
+ Skip **pause** containers

Use kube API proxy

---

.dockerignore
k8s_log_watcher/main.py
k8s_log_watcher/templates/appdynamics.job.jinja2

Adjust Job file with latest version from AppDynamics (``version: 2``)

Fix job config

---

k8s_log_watcher/templates/appdynamics.job.jinja2

Adjust event timestamp format for appdynamics

Adjust event timestamp format

---

k8s_log_watcher/agents/appdynamics.py
k8s_log_watcher/main.py
k8s_log_watcher/templates/appdynamics.job.jinja2

- use app & version.
- add container_name.
- use appdynamics_app & appdynamics_tier labels.
- override existing job files if it is the first run.

Adjust log fields

---

k8s_log_watcher/kube.py
k8s_log_watcher/main.py
tests/test_kube.py

Support multiple namespaces

---

k8s_log_watcher/main.py
k8s_log_watcher/templates/appdynamics.job.jinja2
tests/conftest.py

Use 'application' & 'version' as required labels

Use 'application' & 'version' as required labels

---

.travis.yml
tox.ini

Fix codecov reporting in tox

---

k8s_log_watcher/main.py
k8s_log_watcher/templates/appdynamics.job.jinja2
tests/conftest.py
tests/test_main.py

Add cluster_id log field

---

k8s_log_watcher/agents/__init__.py
k8s_log_watcher/agents/appdynamics.py
k8s_log_watcher/agents/base.py
k8s_log_watcher/agents/scalyr.py
k8s_log_watcher/kube.py
k8s_log_watcher/main.py
k8s_log_watcher/template_loader.py
k8s_log_watcher/templates/appdynamics.job.jinja2
k8s_log_watcher/templates/scalyr.json.jinja2
tests/conftest.py
tests/test_appdynamics.py
tests/test_base.py
tests/test_main.py
tests/test_scalyr.py

- Now supports scalyr and appdynamics (can be set as command line arg or env variable)
Resolve #17

Scalyr support

---

LICENSE
MAINTAINERS
MANIFEST.in
README.rst
kube_log_watcher/main.py

Update README docs

---

README.rst
kube_log_watcher/agents/scalyr.py
kube_log_watcher/kube.py
kube_log_watcher/main.py
kube_log_watcher/templates/scalyr.json.jinja2
requirements.txt
tests/test_scalyr.py

- Adjust Scalyr config with ``copy_from_start`` option.
- Adjust rate limits config for journald monitor plugin.
- Update README with adjusted volume types and initContainer (to avoid log duplication).
- More debug statements.
- Patch pykube client session ``trust_env``. (eliminates the need for ``update-ca-certificates``).
Resolve #30 #28 
Possibly fixing #31

Fix missing logs

---

README.rst

Fix ``initContainer`` command args
Resolve #33

Fix README initContainer

---

MAINTAINERS

Added  ``felix.mueller@zalando.de``.

Updated MAINTAINERS

---

kube_log_watcher/agents/appdynamics.py
kube_log_watcher/agents/scalyr.py
kube_log_watcher/kube.py
kube_log_watcher/main.py

This fixes the flake8 error message.

Fix fix flake "E722 do not use bare except"

---

.zappr.yaml

changed the zappr team to eagleeye.

Change zappr team

---

.zappr.yaml
Dockerfile
README.rst
delivery.yaml

In order to use our cdp-pipeline I added the file `delivery.yaml`.

Added delivery.yaml

---

kube_log_watcher/agents/scalyr.py
kube_log_watcher/templates/scalyr.json.jinja2

This is an exact replica of #51.

Adding support for WATCHER_SCALYR_SERVER

---

kube_log_watcher/templates/scalyr.json.jinja2

fix: add missing quote

---

delivery.yaml
kube_log_watcher/kube.py
kube_log_watcher/main.py
tests/conftest.py
tests/test_kube.py
tests/test_main.py

- Pod labels are now available in container Config Labels
- Add warning when application label is not available
Fix #60

Fix missing labels for some containers

---

README.rst

Strict labels feature is now supported

---

kube_log_watcher/agents/__init__.py
kube_log_watcher/agents/symlinker.py
kube_log_watcher/main.py
tests/conftest.py
tests/test_base.py
tests/test_symlinker.py
tox.ini

Add a Symlinker agent, which creates symlinks with pod metadata encoded in the directory structure. Metadata can then be extracted from the filenames by a log shipping agent such as Fluentd.

Fluentd support

---

kube_log_watcher/agents/scalyr.py
tests/test_scalyr.py

Refactor the code that parses Kubernetes annotations (for Scalyr configuration) in order to make it more testable.

Refactor annotation parsing

---

kube_log_watcher/templates/scalyr.json.jinja2
tests/test_scalyr.py

optimize scalyr-agent sending parameters

optimize scalyr-agent sending parameters

---

kube_log_watcher/templates/scalyr.json.jinja2
tests/test_scalyr.py

As also recommended for testing by Mark O'Brien

increase compression level to 9

---

kube_log_watcher/templates/scalyr.json.jinja2

Makes it easier to work with the configuration files

Remove superfluous newlines

---

delivery.yaml

Use cdp_build_version instead of git tag

remove manual step for release

---

README.rst
delivery.yaml
kube_log_watcher/agents/scalyr.py
kube_log_watcher/agents/symlinker.py
kube_log_watcher/main.py
kube_log_watcher/templates/appdynamics.job.jinja2
kube_log_watcher/templates/scalyr.json.jinja2
tests/conftest.py
tests/test_scalyr.py
tests/test_symlinker.py
tox.ini

Add a `container_id` attribute

Add container_id attribute

---

SECURITY.md

Updating SECURITY.md according to new guidelines.

Updating SECURITY.md

---

README.rst
kube_log_watcher/agents/scalyr.py
kube_log_watcher/main.py
log-watcher.yaml.example
requirements.txt
tests/test_main.py
tests/test_scalyr.py

Override per-application sampling with a global configuration file

Override sampling

---

kube_log_watcher/agents/appdynamics.py
kube_log_watcher/agents/scalyr.py
kube_log_watcher/agents/symlinker.py
kube_log_watcher/kube.py
kube_log_watcher/main.py
tests/test_scalyr.py

Add timestamps to logs

---

kube_log_watcher/main.py
tests/test_main.py

Reset watched containers cache after configuration change

Reset watched containers

---

README.rst
kube_log_watcher/agents/scalyr.py

Add option to decode JSON for all parsers

Add option to decode JSON for all parsers

---

README.rst

Dummy PR to regenerate the Docker Image in order to make it compliant.

Update date - dummy PR

---

README.rst

Another Dummy PR, which updates the README.rst in hopes to finally make Zappr approve the Docker Image properly.

Creating Another Dummy PR

---

README.rst

For testing Zappr and making sure that codecov doesn't block anything.

Another Dummy PR

---

Dockerfile
delivery.yaml

Use latest base image

---

README.rst
tox.ini

https://github.bus.zalan.do/logging/logging-platform/issues/536

removed codecov
